version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root                      # pour pouvoir installer docker-cli
    ports:
      - "8090:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock     # accès au démon Docker
    # on doit aussi installer le client docker dans l’image
    command: >
      /bin/bash -c "
        apt-get update &&
        apt-get install -y docker.io &&
        rm -rf /var/lib/apt/lists/* &&
        /sbin/tini -- /usr/local/bin/jenkins.sh
      "

  api:
    # ... ton service api ...

  web:
    # ... ton service web ...

  test:
    # ... ton service test ...

volumes:
  jenkins_home:
