services:
  jenkins:
    build:
      context: ./service-jenkins
      dockerfile: Dockerfile
    container_name: st-jenkins
    user: root                       # ← Jenkins tourne en root
    privileged: true                 # ← toujours bon pour lever d’éventuels verrous
    ports:
      - "8090:8080"                  # UI Jenkins
      - "50000:50000"                # agents Jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  api:
    build:
      context: ./service-api
    container_name: st-api
    ports:
      - "4000:4000"

  web:
    build:
      context: ./service-web
    container_name: st-web
    depends_on:
      - api
    ports:
      - "8080:80"

  test:
    build:
      context: ./service-test
    container_name: st-test
    depends_on:
      - api
      - web
    # pas de ports exposés — juste pour K6

volumes:
  jenkins_home:
